### PR TITLE
Feature/iconfont/add new window icon

### PR DESCRIPTION
**Pull request by syug**
Added new icon - new-window
Changed current new-window icon to external-link

### CODE REVIEW

**Comment by claudio-moya** [comment]
can you update this pull request by using the new structure for beta version please

**Comment by syug** [comment]
Got it, I'll update this.

**Comment by syug** [comment]
@claudio-moya I merged and updated. Please take a look at it!

**Comment by claudio-moya** [comment]
done! merged into develop thanx! 👍

**Pull request merged**
